project_id: '302424'

files:
  - source: /translation/messages.json
    translation: /translation/%two_letters_code%.json
      languages_mapping:
          two_letters_code:
              zh-CN: zh_cn
              zh-TW: zh_tw
