version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  slack: circleci/slack@3.4.2
commands:
  npm_install:
    description: "Install node modules"
    steps:
      - restore_cache:
          name: Restoring node_modules
          keys:
            - source-v3-modules-{{ checksum "package-lock.json" }}
            - source-v3-modules
      - run:
          name: npm install
          command: npm install
      - save_cache:
          name: Save node_module
          key: source-v3-modules-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
  test:
    description: Test App
    steps:
      - run:
          name: Testing App
          command: npm run test
  build:
    description: Build App
    steps:
      - run:
          name: Building App
          no_output_timeout: 30m
          command: |
            npm run build-travis
            mkdir public
            mv dist/ public/
            cp index.html public/
  versioning:
    description: "Add version to build"
    parameters:
      target_branch:
        type: string
    steps:
      - run:
          name: Tag build
          command: echo "<< parameters.target_branch >> $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > public/version
  docker_build_push:
    description: "Build Docker image"
    parameters:
      docker_latest_image_tag:
        type: string
        default: "latest-staging"
      docker_image_tag:
        type: string
        default: ${CIRCLE_SHA1}
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building docker image
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/binary-static-charts:<< parameters.docker_image_tag >> -t ${DOCKHUB_ORGANISATION}/binary-static-charts:<< parameters.docker_latest_image_tag >> .
      - run:
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/binary-static-charts:<< parameters.docker_image_tag >>
            docker push ${DOCKHUB_ORGANISATION}/binary-static-charts:<< parameters.docker_latest_image_tag >>
  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_version:
        type: string
        default: ${CIRCLE_SHA1}
      k8s_namespace:
        type: string
        default: "charts-binary-com-staging"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster for service binary-charts
          command: |
            export NAMESPACE=<< parameters.k8s_namespace >>
            git clone https://github.com/binary-com/devops-ci-scripts
            cd devops-ci-scripts/k8s-build_tools
            echo $CA_CRT | base64 --decode > ca.crt
            ./release.sh binary-static-charts << parameters.k8s_version >>

  notify_slack:
    description: "Notify slack"
    steps:
      - slack/status:
          include_project_field: false
          failure_message: "Release failed for Smartchart with version *$(cat public/version)*"
          success_message: "Release succeeded for Smartchart with version *$(cat public/version)*"
          webhook: ${SLACK_WEBHOOK}

  publish_to_pages_staging:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (staging)"
          command: |
            npm i wrangler@2.0.19
            cd public
            npx wrangler pages publish . --project-name=smart-charts-pages --branch=staging
            echo "New staging website - http://staging.cf-pages-smart-charts.binary.com"

  publish_to_pages_production:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (production)"
          command: |
            npm i wrangler@2.0.19
            cd public
            npx wrangler pages publish . --project-name=smart-charts-pages --branch=main
            echo "New website - http://cf-pages-smart-charts.binary.com"

jobs:
  test:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - npm_install
      - test
  release_staging:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - npm_install
      - test
      - build
      - versioning:
          target_branch: "staging"
      - persist_to_workspace:
          root: public
          paths:
            - .
      - docker_build_push
      - k8s_deploy
      - notify_slack
  release_production:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - npm_install
      - test
      - build
      - versioning:
          target_branch: "production"
      - persist_to_workspace:
          root: public
          paths:
            - .
      - docker_build_push:
          docker_latest_image_tag: latest
          docker_image_tag: ${CIRCLE_TAG}
      - k8s_deploy:
          k8s_namespace: "charts-binary-com-production"
          k8s_version: ${CIRCLE_TAG}
      - notify_slack

  publish_cloudflare_staging:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - attach_workspace:
          at: public
      - publish_to_pages_staging

  publish_cloudflare_production:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - attach_workspace:
          at: public
      - publish_to_pages_production

workflows:
  test:
    jobs:
      - test:
          filters:
             branches:
               ignore: /^master$/
  release_staging:
    jobs:
      - release_staging:
          filters:
            branches:
              only: /^master$/
          context: binary-frontend-artifact-upload
      - publish_cloudflare_staging:
          requires:
            - release_staging
          filters:
            branches:
              only: /^master$/
          context: binary-frontend-artifact-upload
  release_production:
    jobs:
      - release_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          context: binary-frontend-artifact-upload
      - publish_cloudflare_production:
          requires:
            - release_production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          context: binary-frontend-artifact-upload
