name: Tag for SmartCharts release

permissions: write-all
    
on:   
  workflow_dispatch:
    inputs:
        tag:
            description: 'Tag'
            required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and release tag
        run: |
          git config --global user.name "DerivFE"
          git config --global user.email "fe-access@deriv.com"
          
          git tag ${{ inputs.tag }} ${{ github.ref }}
          git push origin ${{ inputs.tag }}
